import { Globals, Button, Theme, Toggle, StatusBar } from "common.slint";
import { ProgressIndicator } from "std-widgets.slint";

export { Globals }


export component MainWindow inherits Window {
    width: 320px;
    height: 320px;
    background: #ff0000;

    HorizontalLayout {
        alignment: center;
        VerticalLayout {
            alignment: center;
            spacing: 50px;

            Button {
                text: "Hello, World";
                font-size: Theme.font-size-standard;
                height: 50px;
                animate height {
                    duration: 100ms;
                    easing: ease-in;
                }
                states [
                    left-aligned when self.pressed: {
                        height: 80px;
                    }
                ]
            }

            ProgressIndicator {
                width: 100px;
                height: 20px;
            }

            HorizontalLayout {
                Text {
                    width: 120px;
                    text: "Test 123";
                    font-size: Theme.font-size-standard;
                }

                Toggle {
                    width: 100px;
                    clicked => {
                        Globals.toggle-btn(self.on);
                    }
                }
            }

            HorizontalLayout {
                Text {
                    width: 120px;
                    vertical-alignment: center;
                    text: "Pico Calc";
                    font-size: Theme.font-size-standard;
                }

                Rectangle {
                    width: 100px;
                    height: 100px;
                    border-radius: 100px;
                }
            }
        }
    }
}

export component SplashWindow inherits Window {
    width: 320px;
    height: 320px;
    background: #eeeeee;

    VerticalLayout {
        alignment: center;
        spacing: 20px;

        Text {
            text: "Rusty Calc";
            font-size: Theme.font-size-standard;
            horizontal-alignment: center;
        }

        HorizontalLayout {
            alignment: center;
            spacing: 10px;
            Image {
                source: @image-url("images/clockworkpi.png");
                width: 40px;
                height: 40px;
            }

            Image {
                source: @image-url("images/raspberry_pi.svg");
                width: 40px;
                height: 40px;
            }

            Image {
                source: @image-url("images/rust.svg");
                width: 40px;
                height: 40px;
            }

            Image {
                source: @image-url("images/slint.svg");
                width: 40px;
                height: 40px;
            }
        }
    }
}

export component LauncherWindow inherits Window {
    width: 320px;
    height: 320px;
    background: #eeeeee;

    private property <[{name: string, icon: image}]> apps: [
        { name: "Browser", icon: @image-url("images/browser.svg") },
        { name: "Calculator", icon: @image-url("images/calculator.svg") },
        { name: "Clock", icon: @image-url("images/clock.svg") },
        { name: "Contacts", icon: @image-url("images/contacts.svg") },
        { name: "Files", icon: @image-url("images/files.svg") },
        { name: "Games", icon: @image-url("images/games.svg") },
        { name: "Info", icon: @image-url("images/info.svg") },
        { name: "Mail", icon: @image-url("images/mail.svg") },
        { name: "Messages", icon: @image-url("images/messages.svg") },
        { name: "Maps", icon: @image-url("images/maps.svg") },
        { name: "Music", icon: @image-url("images/music.svg") },
        { name: "News", icon: @image-url("images/news.svg") },
        { name: "Notebook", icon: @image-url("images/notebook.svg") },
        { name: "Photos", icon: @image-url("images/photos.svg") },
        { name: "Settings", icon: @image-url("images/settings.svg") },
        { name: "Sheets", icon: @image-url("images/spreadsheet.svg") },
        { name: "Terminal", icon: @image-url("images/terminal.svg") },
        { name: "Translate", icon: @image-url("images/translate.svg") },
        { name: "Weather", icon: @image-url("images/weather.svg") },
    ];
    private property <int> selected: 0;

    private property <bool> shift-pressed: false;

    private property <int> row-count: 4;
    private property <int> column-count: 5;
    private property <length> app-size: 64px;
    private property <length> app-spacing: 0px;

    forward-focus: my-key-handler;
    my-key-handler := FocusScope {
        key-pressed(event) => {
            /*if (event.modifiers.control) {
                debug("control was pressed during this event");
            }
            if (event.text == Key.Escape) {
                debug("Esc key was pressed")
            }*/
            shift-pressed = event.modifiers.shift;
            if (event.text == Key.LeftArrow) {
                if (selected > 0) {
                    selected -= 1;
                }
            }
            if (event.text == Key.RightArrow) {
                if (selected < apps.length - 1) {
                    selected += 1;
                }
            }
            if (event.text == Key.UpArrow) {
                if (selected - column-count >= 0) {
                    selected -= column-count;
                }
            }
            if (event.text == Key.DownArrow) {
                if (selected + column-count < apps.length) {
                    selected += column-count;
                }
            }

            accept
        }

        key-released(event) => {
            if ((event.text == Key.Shift || event.text == Key.ShiftR)) {
                shift-pressed = false;
            }
            accept
        }
    }

    VerticalLayout {

        StatusBar { }

        Rectangle {

            width: (root.column-count * root.app-size) + ((root.column-count + 1) * root.app-spacing);
            height: (root.row-count * root.app-size) + ((root.row-count + 1) * root.app-spacing);
            for app[i] in root.apps: Rectangle {
                x: root.app-spacing + mod(i, root.column-count) * (root.app-size + root.app-spacing);
                y: root.app-spacing + floor(i / (root.row-count + 1)) * (root.app-size + root.app-spacing);
                width: root.app-size;
                height: root.app-size;
                border-width: selected == i ? 2px : 0px;
                border-color: #2F88FF;
                border-radius: 5px;
                Image {
                    source: app.icon;
                    y: 5px;
                }

                Text {
                    text: app.name;
                    y: 44px;
                }
            }
        }

        Text {
            text: "1/1";
            font-size: Theme.font-size-small;
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        Rectangle {
            background: #dddddd;

            VerticalLayout {
                alignment: center;
                visible: !shift-pressed;
                HorizontalLayout {

                    Text {
                        text: "Edit (F1)";
                        font-size: Theme.font-size-small;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        width: 64px;
                    }

                    Text {
                        text: "Sort (F2)";
                        font-size: Theme.font-size-small;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        width: 64px;
                    }

                    Text {
                        text: "View (F3)";
                        font-size: Theme.font-size-small;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        width: 64px;
                    }

                    Text {
                        text: "Opt4 (F4)";
                        font-size: Theme.font-size-small;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        width: 64px;
                    }

                    Text {
                        text: "Help (F5)";
                        font-size: Theme.font-size-small;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        width: 64px;
                    }
                }
            }

            VerticalLayout {
                alignment: center;
                visible: shift-pressed;
                HorizontalLayout {

                    Text {
                        text: "Opt6 (F6)";
                        font-size: Theme.font-size-small;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        width: 64px;
                    }

                    Text {
                        text: "Opt7 (F7)";
                        font-size: Theme.font-size-small;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        width: 64px;
                    }

                    Text {
                        text: "Opt8 (F8)";
                        font-size: Theme.font-size-small;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        width: 64px;
                    }

                    Text {
                        text: "Opt9 (F9)";
                        font-size: Theme.font-size-small;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        width: 64px;
                    }

                    Text {
                        text: "Opt10 (10)";
                        font-size: Theme.font-size-small;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        width: 64px;
                    }
                }
            }
        }
    }
}
