import { Globals, Button, Theme, Toggle } from "common.slint";
import { ProgressIndicator } from "std-widgets.slint";

export { Globals }

export component MainWindow inherits Window {
    width: 320px;
    height: 320px;

    HorizontalLayout {
        alignment: center;
        VerticalLayout {
            alignment: center;
            spacing: 50px;

            Button {
                text: "Hello, World";
                font-size: Theme.font-size-standard;
                height: 50px;
                animate height {
                    duration: 100ms;
                    easing: ease-in;
                }
                states [
                    left-aligned when self.pressed: {
                        height: 80px;
                    }
                ]
            }

                ProgressIndicator {
                    width: 100px;
                    height: 20px;
                    progress: Globals.progress;
                }

            HorizontalLayout {
                Text {
                    width: 120px;
                    text: "Test 123";
                    font-size: Theme.font-size-standard;
                }

                Toggle {
                    width: 100px;
                    clicked => {
                        Globals.toggle-btn(self.on);
                    }
                }
            }

            HorizontalLayout {
                Text {
                    width: 120px;
                    vertical-alignment: center;
                    text: "Pico Calc";
                    font-size: Theme.font-size-standard;
                }

                Rectangle {
                    width: 100px;
                    height: 100px;
                    background: Globals.hardware-user-btn-pressed ? blue : lightgray;
                    border-radius: 100px;
                }
            }
        }
    }
}

export component SplashWindow inherits Window {
    width: 320px;
    height: 320px;
    background: #ffffff;

    VerticalLayout {
        alignment: center;
        spacing: 20px;


        Text {
            text: "Rusty Calc";
            font-size: Theme.font-size-standard;
            horizontal-alignment: center;
        }

        HorizontalLayout {
            alignment: center;
            spacing: 10px;
            Image {
                source: @image-url("images/clockworkpi.png");
                width: 40px;
                height: 40px;
            }

            Image {
                source: @image-url("images/raspberry_pi.svg");
                width: 40px;
                height: 40px;
            }

            Image {
                source: @image-url("images/rust.svg");
                width: 40px;
                height: 40px;
            }

            Image {
                source: @image-url("images/slint.svg");
                width: 40px;
                height: 40px;
            }
        }
    }
}